version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/source"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    registries:
      - ecr-docker
    schedule:
      interval: "weekly"
